Name:           ros-indigo-naoqi-driver
Version:        0.5.6
Release:        0%{?dist}
Summary:        ROS naoqi_driver package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       ros-indigo-cv-bridge
Requires:       ros-indigo-image-transport
Requires:       ros-indigo-kdl-parser
Requires:       ros-indigo-naoqi-bridge-msgs >= 0.0.4
Requires:       ros-indigo-naoqi-libqi
Requires:       ros-indigo-naoqi-libqicore
Requires:       ros-indigo-orocos-kdl
Requires:       ros-indigo-robot-state-publisher
Requires:       ros-indigo-rosbag-storage
Requires:       ros-indigo-tf2-ros
BuildRequires:  boost-devel
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-cv-bridge
BuildRequires:  ros-indigo-diagnostic-msgs
BuildRequires:  ros-indigo-diagnostic-updater
BuildRequires:  ros-indigo-geometry-msgs
BuildRequires:  ros-indigo-image-transport
BuildRequires:  ros-indigo-kdl-parser
BuildRequires:  ros-indigo-naoqi-bridge-msgs >= 0.0.4
BuildRequires:  ros-indigo-naoqi-libqi
BuildRequires:  ros-indigo-naoqi-libqicore
BuildRequires:  ros-indigo-orocos-kdl
BuildRequires:  ros-indigo-robot-state-publisher
BuildRequires:  ros-indigo-rosbag-storage
BuildRequires:  ros-indigo-rosgraph-msgs
BuildRequires:  ros-indigo-sensor-msgs
BuildRequires:  ros-indigo-tf2-geometry-msgs
BuildRequires:  ros-indigo-tf2-msgs
BuildRequires:  ros-indigo-tf2-ros
Conflicts:      ros-indigo-nao-driver
Conflicts:      ros-indigo-naoqi-rosbridge

%description
Driver module between Aldebaran's NAOqiOS and ROS. It publishes all sensor and
actuator data as well as basic diagnostic for battery, termperature. It
subscribes also to RVIZ simple goal and cmd_vel for teleop.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Sun Dec 27 2015 Karsten Knese <karsten.knese@gmail.com> - 0.5.6-0
- Autogenerated by Bloom

* Thu Aug 27 2015 Karsten Knese <karsten.knese@gmail.com> - 0.5.5-0
- Autogenerated by Bloom

* Thu Aug 27 2015 Karsten Knese <karsten.knese@gmail.com> - 0.5.4-0
- Autogenerated by Bloom

* Wed Aug 26 2015 Karsten Knese <karsten.knese@gmail.com> - 0.5.3-0
- Autogenerated by Bloom

* Wed Aug 26 2015 Karsten Knese <karsten.knese@gmail.com> - 0.5.2-0
- Autogenerated by Bloom

* Tue Aug 11 2015 Karsten Knese <karsten.knese@gmail.com> - 0.5.1-0
- Autogenerated by Bloom

* Thu Jul 30 2015 Karsten Knese <karsten.knese@gmail.com> - 0.5.0-0
- Autogenerated by Bloom

