Name:           ros-kinetic-naoqi-driver
Version:        0.5.8
Release:        1%{?dist}
Summary:        ROS naoqi_driver package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       ros-kinetic-cv-bridge
Requires:       ros-kinetic-image-transport
Requires:       ros-kinetic-kdl-parser
Requires:       ros-kinetic-naoqi-bridge-msgs >= 0.0.4
Requires:       ros-kinetic-naoqi-libqi
Requires:       ros-kinetic-naoqi-libqicore
Requires:       ros-kinetic-orocos-kdl
Requires:       ros-kinetic-robot-state-publisher
Requires:       ros-kinetic-rosbag-storage
Requires:       ros-kinetic-tf2-ros
BuildRequires:  boost-devel
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-cv-bridge
BuildRequires:  ros-kinetic-diagnostic-msgs
BuildRequires:  ros-kinetic-diagnostic-updater
BuildRequires:  ros-kinetic-geometry-msgs
BuildRequires:  ros-kinetic-image-transport
BuildRequires:  ros-kinetic-kdl-parser
BuildRequires:  ros-kinetic-naoqi-bridge-msgs >= 0.0.4
BuildRequires:  ros-kinetic-naoqi-libqi
BuildRequires:  ros-kinetic-naoqi-libqicore
BuildRequires:  ros-kinetic-orocos-kdl
BuildRequires:  ros-kinetic-robot-state-publisher
BuildRequires:  ros-kinetic-rosbag-storage
BuildRequires:  ros-kinetic-rosgraph-msgs
BuildRequires:  ros-kinetic-sensor-msgs
BuildRequires:  ros-kinetic-tf2-geometry-msgs
BuildRequires:  ros-kinetic-tf2-msgs
BuildRequires:  ros-kinetic-tf2-ros
Conflicts:      ros-kinetic-nao-driver
Conflicts:      ros-kinetic-naoqi-rosbridge

%description
Driver module between Aldebaran's NAOqiOS and ROS. It publishes all sensor and
actuator data as well as basic diagnostic for battery, termperature. It
subscribes also to RVIZ simple goal and cmd_vel for teleop.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Thu May 19 2016 Surya Ambrose <surya.ambrose@gmail.com> - 0.5.8-1
- Autogenerated by Bloom

* Thu May 19 2016 Surya Ambrose <surya.ambrose@gmail.com> - 0.5.8-0
- Autogenerated by Bloom

