%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/melodic/.*$
%global __requires_exclude_from ^/opt/ros/melodic/.*$

Name:           ros-melodic-naoqi-driver
Version:        0.5.11
Release:        0%{?dist}
Summary:        ROS naoqi_driver package

License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       boost-python2-devel
Requires:       boost-python3-devel
Requires:       ros-melodic-cv-bridge
Requires:       ros-melodic-image-transport
Requires:       ros-melodic-kdl-parser
Requires:       ros-melodic-naoqi-bridge-msgs >= 0.0.4
Requires:       ros-melodic-naoqi-libqi
Requires:       ros-melodic-naoqi-libqicore
Requires:       ros-melodic-orocos-kdl
Requires:       ros-melodic-robot-state-publisher
Requires:       ros-melodic-rosbag-storage
Requires:       ros-melodic-rosconsole
Requires:       ros-melodic-tf2-ros
BuildRequires:  boost-devel
BuildRequires:  boost-python2-devel
BuildRequires:  boost-python3-devel
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-cv-bridge
BuildRequires:  ros-melodic-diagnostic-msgs
BuildRequires:  ros-melodic-diagnostic-updater
BuildRequires:  ros-melodic-geometry-msgs
BuildRequires:  ros-melodic-image-transport
BuildRequires:  ros-melodic-kdl-parser
BuildRequires:  ros-melodic-naoqi-bridge-msgs >= 0.0.4
BuildRequires:  ros-melodic-naoqi-libqi
BuildRequires:  ros-melodic-naoqi-libqicore
BuildRequires:  ros-melodic-orocos-kdl
BuildRequires:  ros-melodic-robot-state-publisher
BuildRequires:  ros-melodic-rosbag-storage
BuildRequires:  ros-melodic-rosconsole
BuildRequires:  ros-melodic-rosgraph-msgs
BuildRequires:  ros-melodic-sensor-msgs
BuildRequires:  ros-melodic-tf2-geometry-msgs
BuildRequires:  ros-melodic-tf2-msgs
BuildRequires:  ros-melodic-tf2-ros
Conflicts:      ros-melodic-nao-driver
Conflicts:      ros-melodic-naoqi-rosbridge

%description
Driver module between Aldebaran's NAOqiOS and ROS. It publishes all sensor and
actuator data as well as basic diagnostic for battery, temperature. It
subscribes also to RVIZ simple goal and cmd_vel for teleop.

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/melodic

%changelog
* Wed Jan 08 2020 Marine Chamoux <mchamoux@softbankrobotics.com> - 0.5.11-0
- Autogenerated by Bloom

